name: Action Test
on:
  issues:
    types: [opened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
      - name: Run Action
        uses: ./action
        with:
          ISSUE_LABELS:
            [ bug ]
          ISSUE_TEMPLATE:
            ./README.md
